services:
  primary:
    image: postgres:16
    container_name: postgres-primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: "--wal-level=replica"
    ports:
      - "5432:5432"
    volumes:
      - ./primary-init:/docker-entrypoint-initdb.d
      - primary_data:/var/lib/postgresql/data

  replica:
    image: postgres:16
    container_name: postgres-replica
    ports:
      - "5433:5432"
    environment:
      PGPASSWORD: replicator_password
    depends_on:
      - primary
    volumes:
      - replica_data:/var/lib/postgresql/data
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        until pg_isready -h primary -p 5432 -U postgres; do
          echo "Waiting for primary database..."
          sleep 2
        done
        rm -rf /var/lib/postgresql/data/*
        pg_basebackup -h primary -D /var/lib/postgresql/data -U replicator -v -P -R -X stream
        
        # FIX: Force the server engine to run under the safe 'postgres' user account
        exec gosu postgres postgres

volumes:
  primary_data:
  replica_data:
